<?php
# 
# This file is part of Roundcube "summary" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2015 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] net
# http://myroundcube.com
# 
$labels=array();$labels['pluginname']='Pàgina Resum';$labels['plugindescription']='Mostra una pàgina de benvinguda després de fer login, amb l\'estat de la bústia i altres paràmetres';$labels['mailbox']='Bústia';$labels['cleanup']='Si us plau, fes neteja';$labels['unfinished']='Tens missatges no finalitzats';$labels['disablesummary']='No mostrar més aquesta plana';$labels['dontusesummary']='No mostrar la plana de resum';$labels['motd']='Missatge del dia';$labels['dst']=' ';$labels['quotawarning']='Si us plau, fes neteja a la bústia, t\'estas quedant sense espai!';$labels['quotafull']='Has excedit la quota de la bústia, si us plau, fes neteja.';