<?php
# 
# This file is part of Roundcube "summary" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2015 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] net
# http://myroundcube.com
# 
$labels=array();$labels['pluginname']='Oversigtsside';$labels['plugindescription']='Viser en velkomstside efter logind med status af postkasse og andre indstillinger.';$labels['description']='Vis postkassens status og andre indstillinger.';$labels['mailbox']='Postkasse';$labels['cleanup']='Ryd venligst op!';$labels['unfinished']='Du har uafsluttet kladder';$labels['disablesummary']='Vis ikke denne side igen';$labels['dontusesummary']='Vis ikke Oversigtsside';$labels['motd']='Beskeder fra i dag';$labels['dst']='DST';$labels['quotawarning']='Ryd venligst op i din postkasse. Du er ved at løbe tør for plads.';$labels['quotafull']='Du har overskredet postkassens størrelse. Ryd venligst op!';$labels['accountsummary']='Konto oversigt';