<?php
# 
# This file is part of Roundcube "summary" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2015 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] net
# http://myroundcube.com
# 
$labels=array();$labels['pluginname']='Startseite';$labels['plugindescription']='Nach der Anmeldung eine Zusammenfassung Ihres Kontos und andere wichtige Information anzeigen.';$labels['mailbox']='Postfach';$labels['cleanup']='Bitte Nachrichten löschen';$labels['unfinished']='Sie haben noch unerledigte Entwürfe';$labels['disablesummary']='Diese Seite nicht mehr anzeigen';$labels['dontusesummary']='Startseite nicht anzeigen';$labels['motd']='Nachrichten';$labels['dst']='Sommerzeit';$labels['quotawarning']='Bitte bereinigen Sie ihr Postfach. Der Speicherplatz ist bald erschöpft.';$labels['quotafull']='Bitte bereinigen Sie ihr Postfach. Der Speicherplatz ist erschöpft.';