<?php
# 
# This file is part of Roundcube "summary" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2015 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] net
# http://myroundcube.com
# 
$labels=array();$labels['pluginname']='Summary Page';$labels['plugindescription']='Show a welcome page after login with mailboxes status summary and other settings.';$labels['mailbox']='Mailbox';$labels['cleanup']='Please cleanup';$labels['unfinished']='You have unfinished drafts';$labels['disablesummary']='Do not show this page again';$labels['dontusesummary']='Do not show summary page';$labels['motd']='Message of the day';$labels['dst']='DST';$labels['quotawarning']='Please clean up your mailbox. You are running out of quota.';$labels['quotafull']='Your mailbox is out of quota. Please clean up.';