<?php
# 
# This file is part of Roundcube "summary" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2015 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] net
# http://myroundcube.com
# 
$labels=array();$labels['pluginname']='Page d\'accueil';$labels['plugindescription']='Affiche une page d’accueil après la connexion avec le statut du compte et d\'autres paramètres de configuration';$labels['description']='Afficher une synthèse du compte et d\'autres paramètres de configuration';$labels['mailbox']='Boite courriel';$labels['cleanup']='Veuillez nettoyer votre boite';$labels['unfinished']='Vous avez des brouillons';$labels['disablesummary']='Ne plus afficher cette page';$labels['dontusesummary']='Ne plus afficher cette page de synthèse';$labels['motd']='Message du jour';$labels['dst']='DST';$labels['quotawarning']='Veuillez vérifier votre compte. Vous atteignez la limite de votre stockage';$labels['quotafull']='Votre boite de courriel est saturée. Veuillez faire un nettoyage';$labels['accountsummary']='Synthèse du compte';