<?php
# 
# This file is part of Roundcube "summary" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2015 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] net
# http://myroundcube.com
# 
$labels=array();$labels['mailbox']='Caixa de correo';$labels['cleanup']='Por favor, borre algunhas mensaxes non necesarias';$labels['unfinished']='Ten borradores pendentes';$labels['disablesummary']='Non volver amosar esta páxina';$labels['dontusesummary']='Non amosar a páxina de resumo';$labels['motd']='Mensaxe do día';$labels['dst']='Horario de verán';$labels['quotawarning']='Queda pouco espacio libre nas súas caixas de correo. Por favor, elimine alguns correos.';$labels['quotafull']='Non queda espacio libre nas súas caixas de correo. Por favor, elimine alguns correos.';