<?php
# 
# This file is part of Roundcube "summary" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2015 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] net
# http://myroundcube.com
# 
$labels=array();$labels['pluginname']='Pagina Riassuntiva';$labels['plugindescription']='Mostra una pagina di benvenuto dopo l\'accesso con lo stato delle caselle di posta e altre configurazioni.';$labels['mailbox']='Casella di posta';$labels['cleanup']='Per favore ripulisci';$labels['unfinished']='Hai bozze incompiute';$labels['disablesummary']='Non visualizzare questa pagina di nuovo';$labels['dontusesummary']='Non visualizzare la pagina riassuntiva';$labels['motd']='Messaggio del giorno';$labels['dst']='DST';$labels['quotawarning']='Per favore rimuovi alcuni messaggi dalla tua casella di posta. La tua casella di posta è al limite della quota assegnata.';$labels['quotafull']='La tua casella di posta è piena. Per favore rimuovi alcuni messaggi.';$labels['accountsummary']='Sommario';