<?php
# 
# This file is part of Roundcube "summary" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2015 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] net
# http://myroundcube.com
# 
$labels=array();$labels['pluginname']='Overzichtspagina';$labels['plugindescription']='Laat een introductiepagina zien na het aanmelden met informatie over uw postvak en instellingen.';$labels['description']='Postvak status en instellingen weergeven';$labels['mailbox']='Postvak';$labels['cleanup']='Postvak opruimen';$labels['unfinished']='U heeft nog onafgemaakte berichten';$labels['disablesummary']='Laat deze pagina niet meer zien';$labels['dontusesummary']='Overzichtspagina niet tonen';$labels['motd']='Bericht van de dag';$labels['dst']='Zomertijd';$labels['quotawarning']='U moet uw postvak opruimen, u heeft haast geen ruimte meer.';$labels['quotafull']='U gebruikt meer data dan is toegestaan. U moet eerst uw postvak opruimen.';$labels['accountsummary']='Account overzicht';