<?php
# 
# This file is part of Roundcube "summary" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2015 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] net
# http://myroundcube.com
# 
$labels=array();$labels['pluginname']='Strona podsumowania';$labels['plugindescription']='Pokazuje stronę przy każdym logowaniu się z informacjami o koncie.';$labels['description']='Pokazuje stronę z informacjami o koncie przy logowaniu.';$labels['mailbox']='Skrzynka pocztowa';$labels['cleanup']='Proszę wyczyścić';$labels['unfinished']='Masz niewysłane kopie robocze';$labels['disablesummary']='Nie pokazuj tej strony ponownie';$labels['dontusesummary']='Nie pokazuj strony z podsumowaniem';$labels['motd']='Wiadomość dnia';$labels['dst']='DST';$labels['quotawarning']='Proszę wyczyścić swoją skrzynkę. Brakuje miejsca.';$labels['quotafull']='Twoje dostępne miejsce na skrzynce zostało przekroczone. Proszę usunąć wiadomości.';$labels['accountsummary']='Informacje o koncie';