<?php
# 
# This file is part of Roundcube "summary" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2015 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] net
# http://myroundcube.com
# 
$labels=array();$labels['pluginname']='Página de Resumo';$labels['plugindescription']='Mostrar uma página de boas-vindas depois do login com o resumo do status da caixa postal e outras configurações.';$labels['mailbox']='Caixa postal';$labels['cleanup']='Por favor, faça uma limpeza';$labels['unfinished']='Você tem rascunhos';$labels['disablesummary']='Não mostrar esta página novamente';$labels['dontusesummary']='Não mostrar a página de resumo';$labels['motd']='Mensagem do dia';$labels['dst']='DST';$labels['quotawarning']='Por favor, limpe sua caixa postal. Você está rodando fora da cota.';$labels['quotafull']='Sua caixa postal está fora da cota. Por favor, limpe-a.';