<?php
# 
# This file is part of Roundcube "summary" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2015 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] net
# http://myroundcube.com
# 
$labels=array();$labels['pluginname']='Página de Resumo';$labels['plugindescription']='Mostrar uma página de boas-vindas após o login com o resumo do estado da caixa de correio e outras configurações.';$labels['mailbox']='Caixa de correio';$labels['cleanup']='Por favor, faça uma limpeza';$labels['unfinished']='Tem rascunhos de mensagens';$labels['disablesummary']='Não mostrar esta página novamente';$labels['dontusesummary']='Não mostrar a página de resumo';$labels['motd']='Mensagem do dia';$labels['dst']='DST';$labels['quotawarning']='Está a atingir o limite máximo da quota de email. Por favor, limpe a sua caixa de correio.';$labels['quotafull']='Atingiu o limite máximo de quota de email. Para libertar espaço, elimine mensagens ou mova-as para uma conta local.';