<?php
# 
# This file is part of Roundcube "summary" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2015 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] net
# http://myroundcube.com
# 
$labels=array();$labels['pluginname']='Резюмирующая Страница';$labels['plugindescription']='Показывает приветственное сообщение после входа пользователя, с информацией о текущем состоянии ящика и разными настройками.';$labels['description']='Показывавет квоты почтового ящика, их расход, и другие настройки';$labels['mailbox']='Почтовый Ящик';$labels['cleanup']='Пожалуйста, очистите';$labels['unfinished']='У вас есть незавершённые черновики';$labels['disablesummary']='Не показывать эту страницу снова';$labels['dontusesummary']='Не показывать страницу с текущим состоянием ящика';$labels['motd']='Сообщение дня';$labels['dst']='DST';$labels['quotawarning']='Пожалуйста, очистите Ваш почтовый ящик. Он переполнен.';$labels['quotafull']='Лимит вашего ящика исчерпан. Пожалуйста, очистите его.';$labels['accountsummary']='Расход квот почтового ящика';